### ISSUE TITLE
New user's name used in admin email "name" field

### ISSUE THREAD

**Issue by nathana212** [strangerstudios/pmpro-email-templates#1]
When admin emails are sent to me (admin address on file), the user's name is used instead of mine. As all the emails use a global header, I don't see an easy way to change this. My assumption is that because the email is often populating with the user's data (membership level, billing, etc.), it is simply filling in the "name" field from that as well.

Here's an example of a recent email...

---

Subject: Member Checkout for Videos in One Take at Courses by Nathan

Dear ecraig21, **[this, as you'll see below, is the USER'S name, not mine, which is Nathan]**

There was a new member checkout at Courses by Nathan.

Below are details about the new membership account and a receipt for the initial membership invoice.

Account: ecraig21 (email address redacted)

Membership Level: Videos in One Take

Membership Fee: The price for membership is $10.00 now.

Invoice #[redacted] on September 2, 2015
Total Billed: $10.00

All the best,
Nathan Agin

---

**Comment by strangerstudios** [comment]
Thanks for the info here. This has come up again and we are working on a fix in the core plugin for this.

**Comment by dparker1005** [comment]
Hi @nathana212,

As this bug has been addressed in a previous release to PMPro, I am going to close this issue. If this is a problem that you are still experiencing after updating to the most recent version of PMPro and PMPro Email Templates, please feel free to create a new issue in this repository so that we can look further into this.
