### ISSUE TITLE
Apostrophe's In Subject Lines are Encoded

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-email-templates#31]
Apostrophe's in Email subjects displays as "&#039;"

**Comment by femiyb** [comment]
https://www.paidmembershipspro.com/forums/topic/email-templates-add-on-apostrophes-in-subject-lines-are-encoded/#post-209897

**Comment by tictag** [comment]
@dparker1005 When you say "Now decodes quotes..", did you mean apostrophes? I guess these are single quotes in 'code-world'. I only ask because my ticket above relates to apostrophes being displayed as `#039;s` in subject lines.

Interestingly, @femiyb initial post actually correctly displays the apostrophe! His comment should have read: "Apostrophe's in Email subjects displays as "# 0 3 9 ; s"" ;-)

**Comment by dparker1005** [comment]
@tictag Yes, that pull request should fix this issue for both single quotes and double quotes (and by extension apostrophes as well). Sorry for the confusion!

**Comment by tictag** [comment]
@dparker1005 Works perfectly! But I guess you knew this already ;-)
